<?php
/**
 * Admin-configurable theme CSS variables.
 *
 * Loaded as a stylesheet (see includes/header.php) so the header, footer and
 * homepage share one set of `:root` custom properties instead of each page
 * carrying its own inline <style> block driven by site_settings colors.
 */
/*
|--------------------------------------------------------------------------
| Response Cache
|--------------------------------------------------------------------------
| This file is requested as a <link rel="stylesheet"> on every single page
| view, so without a cache it ran a full site_settings query and a PHP
| bootstrap on every visitor's every page load. It now serves a plain
| static file for THEME_VARS_CACHE_TTL seconds (regenerated by whichever
| visitor's request finds it stale) and tells the browser to cache it for
| the same window, instead of hitting the database each time.
|--------------------------------------------------------------------------
*/
if (!defined('THEME_VARS_CACHE_TTL')) {
    define('THEME_VARS_CACHE_TTL', 120);
}

$theme_vars_cache_file = __DIR__ . '/../../cache/theme-vars.css';

if (is_file($theme_vars_cache_file) && (time() - filemtime($theme_vars_cache_file)) < THEME_VARS_CACHE_TTL) {
    header('Content-Type: text/css; charset=utf-8');
    header('Cache-Control: public, max-age=' . THEME_VARS_CACHE_TTL);
    readfile($theme_vars_cache_file);
    exit;
}

require_once __DIR__ . '/../../config/db.php';

if (!function_exists('medic_theme_var_table_exists')) {
    function medic_theme_var_table_exists(string $table): bool
    {
        global $pdo;

        try {
            if (!isset($pdo)) {
                return false;
            }

            $stmt = $pdo->prepare("
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.TABLES
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = :table
            ");
            $stmt->execute([':table' => $table]);

            return (int)$stmt->fetchColumn() > 0;
        } catch (Throwable $e) {
            return false;
        }
    }
}

if (!function_exists('medic_theme_var_setting')) {
    function medic_theme_var_setting(string $key, string $default = ''): string
    {
        global $pdo;

        static $settings_cache = null;

        if ($settings_cache === null) {
            $settings_cache = [];

            try {
                if (isset($pdo) && medic_theme_var_table_exists('site_settings')) {
                    $stmt = $pdo->query("SELECT setting_key, setting_value FROM site_settings");

                    foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $row) {
                        $settings_cache[(string)$row['setting_key']] = (string)$row['setting_value'];
                    }
                }
            } catch (Throwable $e) {
                $settings_cache = [];
            }
        }

        $value = trim((string)($settings_cache[$key] ?? ''));

        return $value !== '' ? $value : $default;
    }
}

if (!function_exists('medic_theme_var_color')) {
    function medic_theme_var_color(string $key, string $default): string
    {
        $value = medic_theme_var_setting($key, $default);

        return preg_match('/^#[0-9a-fA-F]{6}$/', $value) ? $value : $default;
    }
}

$primary_color = medic_theme_var_color('primary_color', '#0969da');
$accent_color = medic_theme_var_color('accent_color', '#2da44e');
$secondary_color = medic_theme_var_color('secondary_color', '#14b8a6');
$body_background_color = medic_theme_var_color('body_background_color', '#f6f8fa');

ob_start();
?>
:root {
  --medic-header-dark: #24292f;
  --medic-header-muted: #57606a;
  --medic-header-border: #d0d7de;
  --medic-header-soft: <?= $body_background_color ?>;
  --medic-header-card: #ffffff;
  --medic-header-blue: <?= $primary_color ?>;
  --medic-header-green: <?= $accent_color ?>;
  --medic-header-green-dark: <?= $accent_color ?>;
  --medic-header-shadow: 0 1px 0 rgba(27, 31, 36, 0.04);

  --review-primary: <?= $primary_color ?>;
  --review-accent: <?= $accent_color ?>;
  --review-bg: <?= $body_background_color ?>;

  --dp-primary: <?= $primary_color ?>;
  --dp-accent: <?= $accent_color ?>;
  --dp-bg: <?= $body_background_color ?>;

  --hp-primary: <?= $primary_color ?>;
  --hp-accent: <?= $accent_color ?>;
  --hp-bg: <?= $body_background_color ?>;

  --hospital-primary: <?= $primary_color ?>;
  --hospital-accent: <?= $accent_color ?>;
  --hospital-bg: <?= $body_background_color ?>;

  --footer-primary: <?= $primary_color ?>;
  --footer-accent: <?= $accent_color ?>;
  --footer-bg: <?= $body_background_color ?>;
  --footer-dark: #24292f;
  --footer-muted: #57606a;
  --footer-border: #d0d7de;
  --footer-card: #ffffff;

  --medic-bg: <?= $body_background_color ?>;
  --medic-dark: #0f1720;
  --medic-muted: #57606a;
  --medic-border: #d0d7de;
  --medic-border-soft: #e2e6ea;
  --medic-card: #ffffff;
  --medic-green: <?= $accent_color ?>;
  --medic-green-dark: <?= $accent_color ?>;
  --medic-blue: <?= $primary_color ?>;
  --medic-blue-light: #ddf4ff;
  --medic-purple: <?= $secondary_color ?>;
  --medic-yellow-bg: #fff8c5;
  --medic-yellow-border: #d4a72c;

  --medic-shadow-sm: 0 1px 2px rgba(15, 23, 32, 0.04);
  --medic-shadow-md: 0 12px 28px -12px rgba(15, 23, 32, 0.16);
  --medic-shadow-lg: 0 24px 48px -18px rgba(15, 23, 32, 0.22);
  --medic-radius-sm: 12px;
  --medic-radius-md: 18px;
  --medic-radius-lg: 24px;
  --medic-gradient-brand: linear-gradient(135deg, var(--medic-blue), var(--medic-purple));
  --medic-ring: 0 0 0 4px color-mix(in srgb, var(--medic-blue) 14%, transparent);
  --medic-tint: color-mix(in srgb, var(--medic-blue) 8%, transparent);

  --user-header-dark: #24292f;
  --user-header-muted: #57606a;
  --user-header-border: #d0d7de;
  --user-header-soft: <?= $body_background_color ?>;
  --user-header-card: #ffffff;
  --user-header-blue: <?= $primary_color ?>;
  --user-header-green: <?= $accent_color ?>;
  --user-header-green-dark: <?= $accent_color ?>;
  --user-header-shadow: 0 1px 0 rgba(27, 31, 36, 0.04);
  --user-header-bg: rgba(255, 255, 255, 0.96);
  --user-header-dropdown: #ffffff;
  --user-header-input: #ffffff;
}
<?php
$theme_vars_css = ob_get_clean();

$theme_vars_cache_dir = dirname($theme_vars_cache_file);

if (!is_dir($theme_vars_cache_dir)) {
    @mkdir($theme_vars_cache_dir, 0775, true);
}

if (is_dir($theme_vars_cache_dir) && is_writable($theme_vars_cache_dir)) {
    @file_put_contents($theme_vars_cache_file, $theme_vars_css);
}

header('Content-Type: text/css; charset=utf-8');
header('Cache-Control: public, max-age=' . THEME_VARS_CACHE_TTL);
echo $theme_vars_css;
